In [1]:
import numpy as np

Problem -1
1. Initialize an empty array with size 2X2.

In [ ]:
#problem 1
#1
array = np.empty((2,2))
print(array)

array([[5.37840611e-315, 0.00000000e+000],
       [6.59737730e-310, 1.39067116e-309]])

2. Initialize an all one array with size 4X2.

In [ ]:
#2
array = np.ones((4,2))
print(array)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
#3
array = np.full((2,3), 5)
array

array([[5, 5, 5],
       [5, 5, 5]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
#4
array = np.array([[3, 5, 7],
                [1, 2, 9]])

zero_array = np.zeros_like(array)

print(zero_array)

[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
#5
array = np.array([[1, 3, 7],
                [4, 5, 9]])

one_array = np.ones_like(array)

print(one_array)

[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)

[1 2 3 4]


Problem -2
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
arr = np.arange(10, 50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
array = np.arange(0, 9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
array = np.random.random(30)
mean_value = arr.mean()

print(array)
print("Mean:", mean_value)


[0.35692454 0.32093626 0.41176505 0.80249439 0.1752548  0.58898555
 0.8805911  0.50468249 0.42990076 0.41377766 0.83178648 0.71166729
 0.13607346 0.10361735 0.36946655 0.77522079 0.50342488 0.59205519
 0.66845638 0.0346994  0.44215151 0.72997726 0.0044529  0.04879564
 0.37192128 0.37936481 0.33043503 0.50852716 0.41728714 0.48221712]
Mean: 29.5


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
array = np.random.random((10, 10))

min_val = array.min()
max_val = array.max()

print(array)
print("Minimum Value: ", min_val)
print("Maximum Value: ", max_val)


[[0.55939626 0.89073485 0.91256348 0.44658896 0.9485597  0.2285654
  0.70092368 0.09773551 0.441546   0.81256167]
 [0.56536772 0.89538103 0.42515611 0.26459745 0.78561153 0.05780216
  0.64578439 0.57523887 0.7059577  0.05987139]
 [0.06069497 0.85997095 0.33787181 0.6623702  0.3177664  0.34632372
  0.62434585 0.89596542 0.08516096 0.00456434]
 [0.35466453 0.59322585 0.66140202 0.84190439 0.49091742 0.25016854
  0.47741436 0.49305201 0.03132099 0.93093636]
 [0.1730529  0.19207141 0.66999422 0.60203296 0.84823415 0.36808625
  0.84038416 0.72001373 0.80695021 0.41793775]
 [0.33303748 0.15381119 0.87669327 0.38963564 0.9906058  0.28166709
  0.44440156 0.88073064 0.52901207 0.82272626]
 [0.4831946  0.25358696 0.15464421 0.59492908 0.95993032 0.91708551
  0.65487681 0.60174368 0.18255026 0.20025906]
 [0.47068802 0.8258834  0.90424028 0.53250468 0.84640922 0.94571534
  0.04517635 0.79342115 0.22027287 0.28638219]
 [0.11588125 0.86343162 0.83092964 0.16264618 0.91072476 0.64278381
  0.40729236 

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
array = np.zeros(10)
array[5] = 5;
print(array)

[0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
array = [1, 2, 0, 0, 4, 0]
rev_array = array[::-1]

print(rev_array)

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
array = np.ones((3, 3), dtype=int)
array[1:2, 1:2] = 0
print(array)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checker = np.indices((8, 8)).sum(axis=0)%2
print(checker)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem-3
1. Add the two array.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6], [7,8]])
sum = x + y
print(sum)

[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6], [7,8]])

sub = x-y
print(sub)

[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
v = np.array([9,10])
w = np.array([11,12])

mult = v * w
print(mult)

[ 99 120]


4. Find the square of each element of the array.

In [ ]:
v = np.array([9,10])
w = np.array([11,12])

v_squared = v**2
w_squared = w**2
print(v_squared, w_squared)

[ 81 100] [121 144]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6], [7,8]])
v = np.array([9,10])
w = np.array([11,12])

result1 = np.dot(v, w)
result2 = np.dot(x, v)
result3 = np.dot(x, y)

print(result1)
print(result2)
print(result3)

219
[29 77]
[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [5]:
v = np.array([9,10])
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
w = np.array([11,12])
print("The dot product of v and w is:", np.dot(v,w))
print("The dot product of x and v is:", np.dot(x,v))
print("The dot product of x and y is:", np.dot(x,y))



The dot product of v and w is: 219
The dot product of x and v is: [29 77]
The dot product of x and y is: [[19 22]
 [50 58]]


In [6]:
v = np.array([9,10]);
w = np.array([11,12]);
c = np.concatenate((v,w));
d = np.vstack((v,w));
print(c)
print(d)



[ 9 10 11 12]
[[ 9 10]
 [11 12]]


Problem-4
For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.



In [7]:
a = np.array([[3,4],[7,8]]);
b = np.array([[5,3],[2,1]]);
a_inv=np.linalg.inv(a)
print("This presents the inverse", a_inv)
I= np.dot(a, a_inv)
print("This presents the idenity matrix: ", I)
print( "Result:", np.allclose(I , np.eye(2)))



This presents the inverse [[-2.    1.  ]
 [ 1.75 -0.75]]
This presents the idenity matrix:  [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Result: True


2. Prove AB ̸= BA.

In [8]:
a = np.array([[3,4], [7,8]]);
b = np.array([[5,3], [2,1]]);
ab = a @ b
ba = b @ a
print("AB: ", ab)
print("BA: ", ba)

print("Result:",np.array_equal(ab,ba))

AB:  [[23 13]
 [51 29]]
BA:  [[36 44]
 [13 16]]
Result: False


3. Prove (AB)

In [9]:
a = np.array([[3,4], [7,8]]);
b = np.array([[5,3], [2,1]]);
ab= a@b
ab_transpose=ab.T
b_transpose=b.T
a_transpose=a.T
b_transpose_a_transpose= b_transpose@a_transpose;
print("The transpose of AB",ab_transpose);
print("The transpose of b and a", b_transpose_a_transpose)
print("The output of AB transpose and B transpose A transpose: ", np.array_equal(ab_transpose, b_transpose_a_transpose))



The transpose of AB [[23 51]
 [13 29]]
The transpose of b and a [[23 51]
 [13 29]]
The output of AB transpose and B transpose A transpose:  True


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [10]:


# Coefficient matrix
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constant vector
b = np.array([-1, -3, 9])

# Compute inverse of A
A_inv = np.linalg.inv(A)

# Solve for x
x = A_inv @ b

print("Solution vector [x, y, z] =\n", x)


Solution vector [x, y, z] =
 [ 2.  1. -2.]
